language: java
sudo: false

jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.m2"

before_install:
  - sudo service mysql stop

script:
  - docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PASSWORD}
  - mvn clean package
  - docker build -t tpolishchuk/aqa-training-engine .
  - docker-compose up -d

after_success:
  - docker tag tpolishchuk/aqa-training-engine:latest tpolishchuk/aqa-training-engine:${TRAVIS_BUILD_NUMBER}
  - docker tag tpolishchuk/aqa-training-engine:latest tpolishchuk/aqa-training-engine:latest
  - docker push tpolishchuk/aqa-training-engine
